name: ParchApp
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0
  qrscan: ^0.3.3
  permission_handler: ^10.2.0
  flutter_native_splash: ^2.0.4
  cupertino_icons: ^1.0.2
  flutter_map: ^3.1.0
  geolocator: ^9.0.2
  latlong2: ^0.8.1
  map_launcher: ^2.5.0+1
  firebase_core: ^2.10.0

flutter_native_splash:
  android: true
  ios: true
  web: false

  color: "#FFC107"
  image: "assets/image/PARCHAPP.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/image/

  fonts:
    - family: PlayFair
      fonts:
        - asset: fonts/PlayFairDisplay-Regular.ttf
        - asset: fonts/PlayFairDisplay-Medium.ttf
          weight: 700
        - asset: fonts/PlayFairDisplay-Bold.ttf
          weight: 900
        - asset: fonts/PlayFairDisplay-Italic.ttf
          style: italic

